# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BGS Handbook
email: ScrivenerMods@Gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Scrivener's modding journal and research notes for games made by Bethesda Game Studios.
baseurl: "/BGS-Handbook" # the subpath of your site, e.g. /blog
url: "https://scrivener07.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Scrivener07


# Build settings
theme: minima
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - .gitattributes
  - .gitignore
  - README.md
  - site-serve.ps1
  - site-serve-debug.ps1


# Defaults
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
# Now, this will only set the layout for files where the type is posts.
# The different types that are available to you are pages, posts, drafts or any collection in your site.
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "wiki"
      type: "pages"
    values:
      layout: "wiki"
