# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BGS Handbook
email: ScrivenerMods@Gmail.com
github_username: Scrivener07
description: Scrivener's modding journal and research notes for games made by Bethesda Game Studios.
url: "https://scrivener07.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/BGS-Handbook" # the subpath of your site, e.g. /blog


# Build settings
# https://pages.github.com/themes/
theme: minima

plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   # The default exclusion list.
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Collections
# https://jekyllrb.com/docs/collections/
collections_dir: site_collections
collections:
  site_debug:
    output: true
    permalink: /site/:name
  wiki:
    output: true
    permalink: /:collection/:categories/:name
  wiki_objects_ck:
    output: true
    permalink: /:collection/:categories/:name
  wiki_objects_papyrus:
    output: true
    permalink: /:collection/:categories/:name
  wiki_ui_scaleform:
    output: true
    permalink: /:collection/:categories/:name
  wiki_ui_shared:
    output: true
    permalink: /:collection/:categories/:name
  wiki_ui_menus:
    output: true
    permalink: /:collection/:categories/:name


# Defaults
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
# Now, this will only set the layout for files where the type is posts.
# The different types that are available to you are pages, posts, drafts or any collection in your site.
defaults:
  -
    scope:
      path: ""
      type: "site_debug"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki/page"
  -
    scope:
      path: ""
      type: "wiki_objects_ck"
    values:
      layout: "wiki/page"
  -
    scope:
      path: ""
      type: "wiki_objects_papyrus"
    values:
      layout: "wiki/page"
  -
    scope:
      path: ""
      type: "wiki_ui_scaleform"
    values:
      layout: "wiki/page"
      categories: "fo4 interface reference scripts"
  -
    scope:
      path: ""
      type: "wiki_ui_shared"
    values:
      layout: "wiki/page"
      categories: "fo4 interface reference scripts"
  -
    scope:
      path: ""
      type: "wiki_ui_menus"
    values:
      layout: "wiki/page"
      categories: "fo4 interface reference menus"
  -
    scope:
      path: "assets/object_icon"
    values:
      category: "ck:object:icon"
